import { Router } from "express";
import authRoutes from "./auth.routes";
import checklistRoutes from "./checklist.routes";
import templateRoutes from "./template.routes";
import delegationRoutes from "./delegation.routes";
import transferRoutes from "./transfer.routes";
import userRoutes from "./user.routes";
import departmentRoutes from "./department.routes";
import holidayRoutes from "./holiday.routes";
import systemSettingsRoutes from "./systemSettings.routes";
import uploadRoutes from "./upload.routes";
import otpJobRoutes from "./otpJob.routes";
import otpStageRoutes from "./otpStage.routes";
import pmsJobRoutes from "./pmsJob.routes";
import politicalJobRoutes from "./politicalJob.routes";
import employeeRoutes from "./employee.routes";
import indentRoutes from "./indent.routes";
import enquiryRoutes from "./enquiry.routes";
import followUpRoutes from "./followUp.routes";
import onboardingChecklistRoutes from "./onboardingChecklist.routes";
import leavingRecordRoutes from "./leavingRecord.routes";
import offboardingChecklistRoutes from "./offboardingChecklist.routes";
import leaveRequestRoutes from "./leaveRequest.routes";
import monthlyAttendanceRoutes from "./monthlyAttendance.routes";
import dailyAttendanceRoutes from "./dailyAttendance.routes";
import payrollRoutes from "./payroll.routes";
import misReportRoutes from "./misReport.routes";
import hrDashboardRoutes from "./hrDashboard.routes";
import companyCalendarRoutes from "./companyCalendar.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/checklist", checklistRoutes);
router.use("/templates", templateRoutes);
router.use("/delegation", delegationRoutes);
router.use("/transfer", transferRoutes);
router.use("/users", userRoutes);
router.use("/departments", departmentRoutes);
router.use("/holidays", holidayRoutes);
router.use("/system-settings", systemSettingsRoutes);
router.use("/upload", uploadRoutes);
router.use("/otp-jobs", otpJobRoutes);
router.use("/otp-jobs", otpStageRoutes);
router.use("/pms-jobs", pmsJobRoutes);
router.use("/political-jobs", politicalJobRoutes);
router.use("/employees", employeeRoutes);
router.use("/indents", indentRoutes);
router.use("/enquiries", enquiryRoutes);
router.use("/follow-ups", followUpRoutes);
router.use("/onboarding", onboardingChecklistRoutes);
router.use("/leaving", leavingRecordRoutes);
router.use("/offboarding", offboardingChecklistRoutes);
router.use("/leave-requests", leaveRequestRoutes);
router.use("/attendance/monthly", monthlyAttendanceRoutes);
router.use("/attendance/daily", dailyAttendanceRoutes);
router.use("/payroll", payrollRoutes);
router.use("/mis-report", misReportRoutes);
router.use("/hr-dashboard", hrDashboardRoutes);
router.use("/company-calendar", companyCalendarRoutes);

export default router;
