import { Router } from "express";
import authRoutes from "./auth.routes";
import checklistRoutes from "./checklist.routes";
import templateRoutes from "./template.routes";
import delegationRoutes from "./delegation.routes";
import transferRoutes from "./transfer.routes";
import userRoutes from "./user.routes";
import departmentRoutes from "./department.routes";
import holidayRoutes from "./holiday.routes";
import systemSettingsRoutes from "./systemSettings.routes";
import uploadRoutes from "./upload.routes";
import otpJobRoutes from "./otpJob.routes";
import otpStageRoutes from "./otpStage.routes";
import opsAllotmentRoutes from "./opsAllotment.routes";
import photographerAllotmentRoutes from "./photographerAllotment.routes";
import editorAllotmentRoutes from "./editorAllotment.routes";
import rawDataQcRoutes from "./rawDataQc.routes";
import editingHoursPerJobRoutes from "./editingHoursPerJob.routes";
import editedDataQcRoutes from "./editedDataQc.routes";
import pmsJobRoutes from "./pmsJob.routes";
import politicalJobRoutes from "./politicalJob.routes";
import employeeRoutes from "./employee.routes";
import hrDepartmentRoutes from "./hrDepartment.routes";
import designationRoutes from "./designation.routes";
import vacancyRoutes from "./vacancy.routes";
import jobApplicationRoutes from "./jobApplication.routes";
import indentRoutes from "./indent.routes";
import enquiryRoutes from "./enquiry.routes";
import followUpRoutes from "./followUp.routes";
import onboardingChecklistRoutes from "./onboardingChecklist.routes";
import leavingRecordRoutes from "./leavingRecord.routes";
import offboardingChecklistRoutes from "./offboardingChecklist.routes";
import leaveRequestRoutes from "./leaveRequest.routes";
import monthlyAttendanceRoutes from "./monthlyAttendance.routes";
import dailyAttendanceRoutes from "./dailyAttendance.routes";
import payrollRoutes from "./payroll.routes";
import misReportRoutes from "./misReport.routes";
import hrDashboardRoutes from "./hrDashboard.routes";
import companyCalendarRoutes from "./companyCalendar.routes";
import misRecordRoutes from "./misRecord.routes";
import misCommitmentRoutes from "./misCommitment.routes";
import misKpiKraRoutes from "./misKpiKra.routes";
import misTaskRoutes from "./misTask.routes";
import misChecklistRoutes from "./misChecklist.routes";
import permissionRoutes from "./permission.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/checklist", checklistRoutes);
router.use("/templates", templateRoutes);
router.use("/delegation", delegationRoutes);
router.use("/transfer", transferRoutes);
router.use("/users", userRoutes);
router.use("/departments", departmentRoutes);
router.use("/holidays", holidayRoutes);
router.use("/system-settings", systemSettingsRoutes);
router.use("/upload", uploadRoutes);
router.use("/otp-jobs", otpJobRoutes);
router.use("/otp-jobs", otpStageRoutes);
router.use("/ops-allotments", opsAllotmentRoutes);
router.use("/photographer-allotments", photographerAllotmentRoutes);
router.use("/editor-allotments", editorAllotmentRoutes);
router.use("/raw-data-qc", rawDataQcRoutes);
router.use("/editing-hours-per-job", editingHoursPerJobRoutes);
router.use("/edited-data-qc", editedDataQcRoutes);
router.use("/pms-jobs", pmsJobRoutes);
router.use("/political-jobs", politicalJobRoutes);
router.use("/employees", employeeRoutes);
router.use("/hr-departments", hrDepartmentRoutes);
router.use("/designations", designationRoutes);
router.use("/vacancies", vacancyRoutes);
router.use("/job-applications", jobApplicationRoutes);
router.use("/indents", indentRoutes);
router.use("/enquiries", enquiryRoutes);
router.use("/follow-ups", followUpRoutes);
router.use("/onboarding", onboardingChecklistRoutes);
router.use("/leaving", leavingRecordRoutes);
router.use("/offboarding", offboardingChecklistRoutes);
router.use("/leave-requests", leaveRequestRoutes);
router.use("/attendance/monthly", monthlyAttendanceRoutes);
router.use("/attendance/daily", dailyAttendanceRoutes);
router.use("/payroll", payrollRoutes);
router.use("/mis-report", misReportRoutes);
router.use("/hr-dashboard", hrDashboardRoutes);
router.use("/company-calendar", companyCalendarRoutes);
router.use("/mis-records", misRecordRoutes);
router.use("/mis-commitments", misCommitmentRoutes);
router.use("/mis-kpi-kra", misKpiKraRoutes);
router.use("/mis-tasks", misTaskRoutes);
router.use("/mis-checklist", misChecklistRoutes);
router.use("/permissions", permissionRoutes);

export default router;
